site_name: YOCO
site_url: https://roym899.github.io/yoco/
repo_url: https://github.com/roym899/yoco
repo_name: roym899/yoco
edit_uri: edit/main/docs
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github

extra_css:
  - css/mkdocstrings.css

watch:
  - yoco.py

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            separate_signature: true
            docstring_section_style: "spacy"
            line_length: 75
            members_order: source
            docstring_style: "google"
      enable_inventory: true

nav:
  - Getting started: index.md
  - API Reference: api_reference.md
